// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_cloud_logic = 'enable';
var aws_cloud_logic_custom = [{"id":"qattu00pt3","name":"ReactSample","description":"","endpoint":"https://qattu00pt3.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}];
var aws_cognito_identity_pool_id = 'us-east-1:06cf82cd-090f-44a8-9128-d034b21eb442';
var aws_cognito_region = 'us-east-1';
var aws_content_delivery = 'enable';
var aws_content_delivery_bucket = 'wallet-hosting-mobilehub-742885805';
var aws_content_delivery_bucket_region = 'us-east-1';
var aws_content_delivery_cloudfront = 'enable';
var aws_content_delivery_cloudfront_domain = 'd1oqa6hz06mgn8.cloudfront.net';
var aws_dynamodb = 'enable';
var aws_dynamodb_all_tables_region = 'us-east-1';
var aws_dynamodb_table_schemas = [{"tableName":"wallet-mobilehub-742885805-bbq_orders","attributes":[{"name":"id","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"id"},{"tableName":"wallet-mobilehub-742885805-bbq_restaurants","attributes":[{"name":"id","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"id"},{"tableName":"wallet-mobilehub-742885805-bbq_menu_item","attributes":[{"name":"restaurant_id","type":"S"},{"name":"id","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"restaurant_id","rangeKey":"id"}];
var aws_mandatory_sign_in = 'enable';
var aws_project_id = '0a44347d-1ce3-40aa-bbf7-d11253ab89a6';
var aws_project_name = 'wallet';
var aws_project_region = 'us-east-1';
var aws_resource_bucket_name = 'wallet-deployments-mobilehub-742885805';
var aws_resource_name_prefix = 'wallet-mobilehub-742885805';
var aws_sign_in_enabled = 'enable';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'us-east-1_fj27QUYK3';
var aws_user_pools_mfa_type = 'ON';
var aws_user_pools_web_client_id = '59bese1jgb75r1946a1qpbk9p4';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
